---
pipeline:
  clone:
    - unit_test: deploy
    - build
edges:
  - build: deploy
profiles:
  clone:
    script: ./scripts/fetch.sh
    output: 
      - scm_artifact.tar
    profile_config:
      advance_on:                
        - branch: "*"
          advance_on: "always" 
  unit_test:
    input: 
      - scm_artifact.tar
    script: ./scripts/unit_test.sh
    profile_config:
      advance_on:                
        - branch: "*"
          advance_on: "always"
  build:
    input: 
      - scm_artifact.tar
    script: ./scripts/build.sh
    output: 
      - build_artifact.tar
    profile_config:
      advance_on:                
        - branch: "*"
          advance_on: "always"  
  deploy:
    input: 
      - build_artifact.tar
    script: ./scripts/deploy.sh
    environment:
      DOCKER_IMAGE: predixci/canary
      DOCKER_USERNAME: predixci
      # DOCKER_PASSWORD: set in Predix CI UI
      # SOLANO_API_KEY:  set in Predix CI UI
  default:
    script: dev/null
