---
pipeline:
  unit_test: deploy
profiles:
  unit_test:
    input: 
      - scm_artifact.tar
    script: ./scripts/unit_test.sh
  deploy:
    input: 
      - build_artifact.tar
    script: ./scripts/deploy.sh
  default:
    script: dev/null
